[package]
name = "enrique/knittest"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
knit = "sleitnick/knit@1.0.9"
Comm = "sleitnick/comm@0.1.2"
Component = "sleitnick/component@2.0.0"	
EnumList = "sleitnick/enum-list@1.0.2"
Input = "sleitnick/input@1.1.0"
Loader = "sleitnick/loader@1.0.2"
Log = "sleitnick/log@0.1.0"
Option = "sleitnick/option@1.0.2"
PID = "sleitnick/pid@1.0.1"
Ser = "sleitnick/ser@1.0.3"
Signal = "sleitnick/signal@1.0.1"
Streamable = "sleitnick/streamable@1.1.0"
Symbol = "sleitnick/symbol@1.0.1"
TableUtil = "sleitnick/table-util@1.1.1"
TaskQueue = "sleitnick/task-queue@0.1.0"
Timer = "sleitnick/timer@1.0.3"
Trove = "sleitnick/trove@0.1.3"                 
maid = "finobinos/maid@3.2.1"