[package]
name = "sleitnick/knit-bundle"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Component = "sleitnick/component@^1"
EnumList = "sleitnick/enum-list@^1"
Option = "sleitnick/option@^1"
Signal = "sleitnick/signal@^1"
TableUtil = "sleitnick/table-util@^1"
Timer = "sleitnick/timer@^1"
Trove = "sleitnick/trove@^0.1"
Comm = "sleitnick/comm@^0.1"
Promise = "evaera/promise@^3.1"
