[package]
name = "sleitnick/loader"
description = "Requires all modules within a given instance"
version = "1.0.2"
license = "MIT"
authors = ["Stephen Leitnick"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
