[package]
name = "sleitnick/knit"
description = "Knit is a lightweight game framework"
version = "1.0.9"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Loader = "sleitnick/loader@^1.0"
Signal = "sleitnick/signal@^1.0"
Comm = "sleitnick/comm@^0.1"
TableUtil = "sleitnick/table-util@^1.0"
Promise = "evaera/promise@^3.1"
