[package]
name = "sleitnick/component"
description = "Component class"
version = "1.1.0"
license = "MIT"
authors = ["Stephen Leitnick"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Signal = "sleitnick/signal@^1.0"
TableUtil = "sleitnick/table-util@^1.0"
Trove = "sleitnick/trove@^0.1"
Promise = "evaera/promise@^3.1"
